### ISSUE TITLE
Hot reloading does not work

### ISSUE THREAD

**Issue by kolis** [mobxjs/mobx-react-boilerplate#3]
I really appreciate this template project, but can not get it to work properly. I can run the server but the hot reloading does not seem to work. I get this output in the browser console.
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 76
[HMR] Nothing hot updated.
[HMR] App is up to date.
```
After eg changing
`appState.timer += 1;`
to
`appState.timer += 10;`

**Comment by mweststrate** [comment]
Hi, 

I didn't dive into the details how hot reloading exactly work, but in general it does seem to support changes to react components and modules that just expose functions. Since this boilerplate puts all stuff into one file (for convenience), the usefulness of the HMR is limited (maybe I should remove it from the boilerplate?). A better example is this repo: https://github.com/mobxjs/mobx-reactive2015-demo. It uses separate files for each component (which you would do in a real project) and then hot-reloading works correctly for most files.

**Comment by kolis** [comment]
Ok, tnx for explanation! But yes, it would be preferable if the provided example components allowed HMR
